FROM rust:1.70 AS builder
WORKDIR /usr/src/wololo
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /usr/src/wololo/target/release/wololo /usr/local/bin/wololo
RUN apt-get update && apt-get install -y ca-certificates
VOLUME /etc/wololo
CMD ["wololo", "/etc/wololo/db.yaml"]
